#!/bin/sh
# source debconf stuff
. /usr/share/debconf/confmodule
dbc_generate_include_owner="root:www-data"
dbc_generate_include_perms="0640"
dbc_generate_include=template:/etc/groupoffice/config.ini
dbc_generate_include_args="-U -o template_infile='/usr/share/doc/groupoffice/config.ini.tpl'"
       
. /usr/share/dbconfig-common/dpkg/postinst
dbc_go groupoffice "$@"

a2enconf groupoffice
systemctl reload apache2

chown www-data:www-data /var/lib/groupoffice
